name: Build & Release AppImage

on:
  push:
    tags:
      - "v*.*.*"   # Se lance uniquement sur push de tags versionnés
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: scxctl_gui
          path: ./*.AppImage

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: scxctl_gui
          path: ./release

      - name: Create GitHub Release and upload AppImage
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
