name: Build & Test Portable AppImage

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6
      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run portable build script
        run: ./build.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: scxctl_gui
          path: build_out/*.AppImage

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build_out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
