name: Build AppImage

on:
  push:
    tags:
      - "v*.*.*"   # Se lance uniquement lors du push d'un tag versionné (ex: v1.0.0)
  workflow_dispatch:  # Permet de lancer manuellement si besoin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: scxctl_gui
          path: ./*.AppImage

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: scxctl_gui
          path: ./release

      # Cette étape empêche la release si le workflow est lancé manuellement sans tag
      - name: Vérifier la présence d’un tag
        run: |
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            echo "Aucun tag trouvé. Veuillez créer un tag avant la release."
            exit 1
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
